"""empty message

Revision ID: f070e05d3021
Revises: 9197038171a3
Create Date: 2021-08-17 22:38:21.921570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f070e05d3021'
down_revision = '9197038171a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_meals', 'count')
    op.drop_column('order_meals', 'sum')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_meals', sa.Column('sum', mysql.FLOAT(), nullable=True))
    op.add_column('order_meals', sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
